### ISSUE TITLE
Error when queuing Xamarin.iOS build

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#241]
When I queue a build this error shows on my agent console window
2016-03-07T14:11:37.317Z: Agent Started.
unhandled:toString failed
Error: toString failed
    at Buffer.toString (buffer.js:385:11)
    at RollingDiagnosticFileWriter._initializeFileQueue (/Users/AgilxAdmin/agent4/agent/diagnostics.js:117:72)
    at new RollingDiagnosticFileWriter (/Users/AgilxAdmin/agent4/agent/diagnostics.js:47:14)
    at Object.getDefaultDiagnosticWriter (/Users/AgilxAdmin/agent4/agent/diagnostics.js:159:12)
    at getWorkerDiagnosticWriter (/Users/AgilxAdmin/agent4/agent/vsoworker.js:43:15)
    at run (/Users/AgilxAdmin/agent4/agent/vsoworker.js:52:48)
    at process.<anonymous> (/Users/AgilxAdmin/agent4/agent/vsoworker.js:141:22)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:689:10)

On the visualstudio.com the build shows as queued but none of the build steps show up and it never gets latest. I attempt to cancel the job and then this line shows up in the console
##[Error] 2016-03-07T14:13:48.488Z: Unknown Message Type: JobCancellation

**Comment by rusty21** [comment]
I've tried updating the agent, no effect.

**Comment by madhurig** [comment]
What version of the agent do you have? This error as the stack indicates causes diagnostics to not be written correctly. I see the same "Unknown Message Type: JobCancellation" and similar errors on logging sometimes, but my build actually runs. Also check the status of the agent in the web and see if it shows "Green" or "Red". 

Try switching to the stable version of the agent: "curl -skSL http://aka.ms/xplatagent | bash" if you are on latest. If you are using the stable version, could you try the latest preview version: "curl -skSL http://aka.ms/previewxplat | bash"

Thanks,
Madhuri

**Comment by rusty21** [comment]
I reinstalled the agent and it appears to be working. I don't know what I did to break the agent but it's working now.
