### ISSUE TITLE
vso-agent mac: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by simplatek** [Microsoft/vso-agent#242]
When I successfully start a build agent on the mac for an iOS project, the agent starts up and authenticates to VSTS just fine, but once it tries to execute the build definition I encounter the following error:

this is what I have installed : vsoagent-installer@0.5.7

2016-02-26T22:15:37.314Z: Running job: Build
unhandled:Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
    at TaskCompleteCommand.runCommand (/Users/jhermann/myagent/agent/commands/task.complete.js:16:23)
    at _handleCommand (/Users/jhermann/myagent/agent/handlers/scriptrunner.js:36:17)
    at _processLine (/Users/jhermann/myagent/agent/handlers/scriptrunner.js:12:9)
    at /Users/jhermann/myagent/agent/handlers/scriptrunner.js:129:13
    at _handleData (/Users/jhermann/myagent/agent/handlers/scriptrunner.js:112:13)
    at Socket.<anonymous> (/Users/jhermann/myagent/agent/handlers/scriptrunner.js:128:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)

**Comment by roel4ez** [comment]
I'm having the exact same issue, ever since we updated to TFS2015.2 RC2. I've updated the agent to the latest version (node 5.6.0  TEE CLI 14.0.2).
It seems the result is not available in the properties set.

**Comment by roel4ez** [comment]
I've tried to install a second agent on the same machine, but the same error keeps happening. This is at the moment a showstopper for us, as we cannot do any iOS builds on the server.

**Comment by simplatek** [comment]
just updated to v0.6.3 and xcode builds are working now, don't know what version fixed it but latest is producing ipa's for me.

**Comment by bryanmacfarlane** [comment]
Great.  Thanks for confirming it's fixed.
